// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzoawkshatzlioyjxjlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6b2F3a3NoYXR6bGlveWp4amx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjIzNTEsImV4cCI6MjA3MTI5ODM1MX0.HPDUM4hDSSzj1orLbJo12_-hVILb_1V4P9Xp7oIqvNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});